# Generated by Django 5.2.1 on 2025-05-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='watched_episodes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
