# Generated by Django 5.2.1 on 2025-05-31 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0006_userprofile_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, help_text='HEX или CSS-цвет для бейджа', max_length=16, null=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='color_profile', to='auth.group')),
            ],
        ),
    ]
