# Generated by Django 5.2.1 on 2025-05-31 18:19

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tag_news_newsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='Содержание (Markdown)'),
        ),
    ]
