# Generated by Django 5.2.1 on 2025-05-31 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_news_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
    ]
