# Generated by Django 5.2.1 on 2025-05-31 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_news_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('watching', 'Смотрю'), ('planned', 'Запланировано'), ('completed', 'Просмотрено')], max_length=16)),
                ('watched_episodes', models.PositiveIntegerField(default=0)),
                ('event_type', models.CharField(choices=[('add', 'Добавление'), ('remove', 'Удаление'), ('status', 'Смена статуса'), ('episodes', 'Изменение серий')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История закладок',
                'verbose_name_plural': 'История закладок',
                'ordering': ['-created_at'],
            },
        ),
    ]
