# Generated by Django 5.2.1 on 2025-06-02 11:55

import django.db.models.deletion
import mdeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_bookmarkhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название товара')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL slug')),
                ('description', mdeditor.fields.MDTextField(verbose_name='Описание товара (Markdown)')),
                ('short_description', models.TextField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='Характеристики товара')),
                ('is_digital', models.BooleanField(default=True, verbose_name='Цифровой товар')),
                ('stock_quantity', models.PositiveIntegerField(default=999, verbose_name='Количество на складе')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL slug')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Цвет категории')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка (emoji или класс)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категория товаров',
                'verbose_name_plural': 'Категории товаров',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название скидки')),
                ('percentage', models.PositiveIntegerField(verbose_name='Процент скидки (1-99)')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('max_activations', models.PositiveIntegerField(default=1, verbose_name='Максимальное количество активаций')),
                ('activations_used', models.PositiveIntegerField(default=0, verbose_name='Использовано активаций')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='core.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='core.productcategory', verbose_name='Категории'),
        ),
        migrations.CreateModel(
            name='DiscountActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата активации')),
                ('order_id', models.CharField(blank=True, max_length=100, verbose_name='ID заказа')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='core.discount', verbose_name='Скидка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_activations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Активация скидки',
                'verbose_name_plural': 'Активации скидок',
                'ordering': ['-activated_at'],
                'unique_together': {('discount', 'user')},
            },
        ),
    ]
