# Generated by Django 5.2.1 on 2025-06-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название ящика (для отображения)', max_length=64)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('imap_server', models.CharField(max_length=128)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('smtp_server', models.CharField(max_length=128)),
                ('smtp_port', models.PositiveIntegerField(default=465)),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
