# Generated by Django 5.2.1 on 2025-06-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_emailaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='imap_server',
            field=models.CharField(default='imap.mail.ru', max_length=128),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='smtp_server',
            field=models.CharField(default='smtp.mail.ru', max_length=128),
        ),
    ]
