# Generated by Django 5.2.1 on 2025-06-04 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_emailaccount_imap_server_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название способа оплаты')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Идентификатор')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='payment_methods/', verbose_name='Иконка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('processor_type', models.CharField(choices=[('anypay', 'AnyPay'), ('manual', 'Ручная обработка'), ('crypto', 'Криптовалюта'), ('bank', 'Банковский перевод')], default='anypay', max_length=50, verbose_name='Тип обработчика')),
                ('processor_config', models.JSONField(blank=True, default=dict, verbose_name='Настройки обработчика')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payments_enabled', models.BooleanField(default=True, verbose_name='Оплата включена')),
                ('maintenance_message', models.TextField(blank=True, default='Оплата временно отключена. Попробуйте позже.', verbose_name='Сообщение при отключенной оплате')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки магазина',
                'verbose_name_plural': 'Настройки магазина',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paymentmethod', verbose_name='Способ оплаты'),
        ),
    ]
