# Generated by Django 5.2.1 on 2025-06-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_paymentmethod_shopsettings_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('redirect', 'Перенаправление на платежную систему'), ('manual', 'Ручная обработка'), ('crypto', 'Криптовалюта'), ('bank', 'Банковский перевод')], max_length=20, null=True, verbose_name='Тип оплаты'),
        ),
    ]
