# Generated by Django 5.2.1 on 2025-06-13 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_order_payment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='room',
            name='allow_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='allow_guests',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='anime_id',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='processor_type',
            field=models.CharField(choices=[('anypay', 'AnyPay'), ('robokassa', 'RoboKassa'), ('manual', 'Ручная обработка'), ('crypto', 'Криптовалюта'), ('bank', 'Банковский перевод')], default='anypay', max_length=50, verbose_name='Тип обработчика'),
        ),
    ]
