# Generated by Django 5.2.1 on 2025-06-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_order_payment_type_room_allow_control_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='allow_guests',
        ),
    ]
