# Generated by Django 5.2.1 on 2025-06-20 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_comment_options_comment_likes_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('bulk_delete', 'Массовое удаление'), ('status_change', 'Изменение статуса'), ('permission_change', 'Изменение прав'), ('system_action', 'Системное действие')], max_length=20)),
                ('entity_type', models.CharField(choices=[('user', 'Пользователь'), ('news', 'Новость'), ('comment', 'Комментарий'), ('room', 'Комната'), ('product', 'Товар'), ('category', 'Категория'), ('order', 'Заказ'), ('settings', 'Настройки')], max_length=20)),
                ('entity_id', models.CharField(max_length=255)),
                ('entity_name', models.CharField(max_length=500)),
                ('old_data', models.JSONField(blank=True, default=dict)),
                ('new_data', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_reverted', models.BooleanField(default=False)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('revert_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('reverted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог действий администратора',
                'verbose_name_plural': 'Логи действий администраторов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminActionRevert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revert_reason', models.TextField()),
                ('revert_data', models.JSONField(default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revert_record', to='core.adminactionlog')),
                ('reverted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_reverts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Откат действия администратора',
                'verbose_name_plural': 'Откаты действий администраторов',
            },
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['admin_user', '-created_at'], name='core_admina_admin_u_3adcd6_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='core_admina_entity__cbfee4_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['action_type', '-created_at'], name='core_admina_action__1c16f0_idx'),
        ),
    ]
