"""
Django settings for backend_v2 project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(xa1b(gie^c=t#%%^@)wyo3c836wewvl0#2x4^0-*fg%xn5%2e'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = False


# Для production-режима обязательно укажите домены/IP, с которых разрешён доступ.
# Например: ['127.0.0.1', 'localhost', 'yourdomain.com']
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'anirase.ru',"https://anirase.ru", "192.168.0.100"]
CSRF_TRUSTED_ORIGINS = [
    "https://anirase.ru",
    "https://auth.robokassa.ru",
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'mdeditor',  # django-mdeditor
    'core',
]

INSTALLED_APPS += [
    'channels',
    # Для поддержки ImageField (аватар):
    # 'core.userprofile_models',  # если потребуется явный импорт (удалено)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend_v2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_v2.wsgi.application'
ASGI_APPLICATION = 'backend_v2.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'anirase',
        'USER': 'anirase',
        'PASSWORD': 'nuf38hdfg34',
        'HOST': '80.82.39.95',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=366),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

CORS_ALLOW_ALL_ORIGINS = True

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# ---
# Настройки для загрузки медиафайлов (аватары пользователей)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ---
# Для ImageField требуется Pillow:
# pip install Pillow
# ---

# MDEditor настройки
MDEDITOR_CONFIGS = {
    'default': {
        'width': '100%',
        'height': 500,
        'toolbar': ["undo", "redo", "|",
                   "bold", "del", "italic", "quote", "ucwords", "uppercase", "lowercase", "|",
                   "h1", "h2", "h3", "h5", "h6", "|",
                   "list-ul", "list-ol", "hr", "|",
                   "link", "reference-link", "image", "code", "preformatted-text", "code-block", "table", "datetime",
                   "emoji", "html-entities", "pagebreak", "goto-line", "|",
                   "help", "info",
                   "||", "preview", "watch", "fullscreen"],
        'upload_image_formats': ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
        'image_folder': 'editor',
        'theme': 'default',  # dark / default
        'preview_theme': 'default',  # dark / default
        'editor_theme': 'default',  # pastel-on-dark / default
        'toolbar_autofixed': True,
        'search_replace': True,
        'emoji': True,
        'tex': True,
        'flow_chart': True,
        'sequence': True,
        'watch': True,
        'lineWrapping': False,
        'lineNumbers': False,
        'language': 'ru'
    }
}

DEFAULT_FROM_EMAIL = 'no-repl@anirase.ru'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.mail.ru'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'no-repl@anirase.ru'
EMAIL_HOST_PASSWORD = 'AQHrppjcrEZVBtNQoGIG'  # Замените на реальный пароль
EMAIL_USE_SSL = True

JAZZMIN_SETTINGS = {
    "site_title": "AniRase Admin",
    "site_header": "Панель управления AniRase",
    "site_brand": "AniRase",
    "welcome_sign": "Добро пожаловать в админку AniRase!",
    "copyright": "AniRase",
    "search_model": ["core.Product", "core.News", "core.UserProfile"],    "order_with_respect_to": [
        "core.ShopSettings",
        "core.PaymentMethod",
        "core.ProductCategory",
        "core.Product",
        "core.Discount",
        "core.DiscountActivation",
        "core.Order",
        "core.News",
        "core.NewsImage",
        "core.Tag",
        "core.Bookmark",
        "core.BookmarkHistory",
        "core.Comment",
        "core.UserProfile",
        "core.GroupColor",
        "core.History",
        "core.Room",
        "core.RoomSession",
    ],    "icons": {
        "core.ShopSettings": "fas fa-cog",
        "core.PaymentMethod": "fas fa-credit-card",
        "core.Product": "fas fa-box",
        "core.ProductCategory": "fas fa-tags",
        "core.Discount": "fas fa-percent",
        "core.DiscountActivation": "fas fa-ticket-alt",
        "core.Order": "fas fa-receipt",
        "core.News": "fas fa-newspaper",
        "core.NewsImage": "fas fa-image",
        "core.Tag": "fas fa-tag",
        "core.Bookmark": "fas fa-bookmark",
        "core.BookmarkHistory": "fas fa-history",
        "core.Comment": "fas fa-comments",
        "core.UserProfile": "fas fa-user",
        "core.GroupColor": "fas fa-palette",
        "core.History": "fas fa-eye",
        "core.Room": "fas fa-users",
        "core.RoomSession": "fas fa-user-clock",
    },
    # "site_logo": "AniRase.webp",    
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "show_sidebar": True,
    "navigation_expanded": True,
    "language_chooser": False,
    "related_modal_active": True,
    "topmenu_links": [
        {"name": "Frontend", "url": "https://anirase.ru", "new_window": False},
        {"name": "Github", "url": "https://github.com/vitaluska123/AniRase", "new_window": True},
        {"name": "Cloudflare", "url": "https://dash.cloudflare.com/882764ed5a13018664590b1a3d095256/anirase.ru/dns/records", "new_window": True},
        {"name": "AnyPay", "url": "https://anypay.io/panel/project/16480", "new_window": True},
        {"name": "Отчёты и графики", "url": "/admin/core/userprofile/reports-dashboard/", "new_window": False},
        {"name": "Почта (ящики)", "url": "/admin/core/emailaccount/reports-mail-dashboard/", "new_window": False}
    ],
    # "show_ui_builder": True,
}
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "superhero",
    "dark_mode_theme": "superhero",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

ANYPAY_API_KEY = 'bSR2oIQiT5XSUExYlLklT8cIX9ZqQ4oVaFQfT7Q'
ANYPAY_SHOP_ID = '16480'
SITE_URL = 'https://anirase.ru'  # или http://127.0.0.1:8034 для локальной разработки

YANDEX_PARTNER_API_KEY = 'y0__xD238a_BRjnjC0g3rLDsBOyZlmMfx8mxWOuRIKQnoqSW_854A'

# RoboKassa настройки
ROBOKASSA_LOGIN = 'anirase'  # Ваш логин в RoboKassa
ROBOKASSA_PASSWORD1 = 'OFtqmt35LlBj7zJWuM33'  # Пароль #1 (для тестового режима)
ROBOKASSA_PASSWORD2 = 'WQ4hCiT4PVV696prJuIs'  # Пароль #2 (для тестового режима)
ROBOKASSA_TEST_MODE = True  # True для тестового режима
ROBOKASSA_HASH_ALGO = 'sha256'  # Алгоритм хеширования: md5, sha1, sha256, sha384, sha512
